-- MySQL Script generated by MySQL Workbench
-- Fri Jul 23 08:49:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema calificador_creaj
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema calificador_creaj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `calificador_creaj` DEFAULT CHARACTER SET utf8 ;
USE `calificador_creaj` ;

-- -----------------------------------------------------
-- Table `calificador_creaj`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usario` VARCHAR(45) NULL,
  `nombres` VARCHAR(50) NULL,
  `apellidos` VARCHAR(50) NULL,
  `rol` CHAR(1) NULL,
  `password` VARCHAR(40) NULL,
  `email` VARCHAR(70) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `calificador_creaj`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`estudiante` (
  `idestudiante` VARCHAR(8) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  PRIMARY KEY (`idestudiante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `calificador_creaj`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`nivel` (
  `idnivel` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idnivel`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `calificador_creaj`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`grado` (
  `idgrado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `seccion` VARCHAR(45) NULL,
  `nivel_idnivel` INT NOT NULL,
  PRIMARY KEY (`idgrado`, `nivel_idnivel`),
  INDEX `fk_grado_nivel1_idx` (`nivel_idnivel` ASC) VISIBLE,
  CONSTRAINT `fk_grado_nivel1`
    FOREIGN KEY (`nivel_idnivel`)
    REFERENCES `calificador_creaj`.`nivel` (`idnivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `calificador_creaj`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`materia` (
  `idmateria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idmateria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `calificador_creaj`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`proyecto` (
  `idproyecto` INT NOT NULL AUTO_INCREMENT,
  `nombreProyecto` VARCHAR(45) NULL,
  `descripcion` MEDIUMTEXT NULL,
  `grado_idgrado` INT NOT NULL,
  `materia_idmateria` INT NOT NULL,
  PRIMARY KEY (`idproyecto`, `grado_idgrado`, `materia_idmateria`),
  INDEX `fk_proyecto_grado1_idx` (`grado_idgrado` ASC) VISIBLE,
  INDEX `fk_proyecto_materia1_idx` (`materia_idmateria` ASC) VISIBLE,
  CONSTRAINT `fk_proyecto_grado1`
    FOREIGN KEY (`grado_idgrado`)
    REFERENCES `calificador_creaj`.`grado` (`idgrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `calificador_creaj`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `calificador_creaj`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`equipo` (
  `idequipo` INT NOT NULL AUTO_INCREMENT,
  `estudiante_idestudiante` VARCHAR(8) NOT NULL,
  `proyecto_idproyecto` INT NOT NULL,
  PRIMARY KEY (`idequipo`, `estudiante_idestudiante`, `proyecto_idproyecto`),
  INDEX `fk_equipo_estudiante_idx` (`estudiante_idestudiante` ASC) VISIBLE,
  INDEX `fk_equipo_proyecto1_idx` (`proyecto_idproyecto` ASC) VISIBLE,
  CONSTRAINT `fk_equipo_estudiante`
    FOREIGN KEY (`estudiante_idestudiante`)
    REFERENCES `calificador_creaj`.`estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo_proyecto1`
    FOREIGN KEY (`proyecto_idproyecto`)
    REFERENCES `calificador_creaj`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `calificador_creaj`.`rubrica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`rubrica` (
  `idrubrica` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `materia_idmateria` INT NOT NULL,
  `nivel_idnivel` INT NOT NULL,
  PRIMARY KEY (`idrubrica`, `materia_idmateria`, `nivel_idnivel`),
  INDEX `fk_rubrica_materia1_idx` (`materia_idmateria` ASC) VISIBLE,
  INDEX `fk_rubrica_nivel1_idx` (`nivel_idnivel` ASC) VISIBLE,
  CONSTRAINT `fk_rubrica_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `calificador_creaj`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rubrica_nivel1`
    FOREIGN KEY (`nivel_idnivel`)
    REFERENCES `calificador_creaj`.`nivel` (`idnivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `calificador_creaj`.`criterios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`criterios` (
  `idcriterios` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `puntaje` INT NULL,
  `rubrica_idrubrica` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idcriterios`, `rubrica_idrubrica`),
  INDEX `fk_criterios_rubrica1_idx` (`rubrica_idrubrica` ASC) VISIBLE,
  CONSTRAINT `fk_criterios_rubrica1`
    FOREIGN KEY (`rubrica_idrubrica`)
    REFERENCES `calificador_creaj`.`rubrica` (`idrubrica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `calificador_creaj`.`asignacionJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`asignacionJ` (
  `idasignacionJ` INT NOT NULL AUTO_INCREMENT,
  `usuario_idUsuario` INT NOT NULL,
  `materia_idmateria` INT NOT NULL,
  `grado_idgrado` INT NOT NULL,
  PRIMARY KEY (`idasignacionJ`, `usuario_idUsuario`, `materia_idmateria`, `grado_idgrado`),
  INDEX `fk_asignacionJ_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_asignacionJ_materia1_idx` (`materia_idmateria` ASC) VISIBLE,
  INDEX `fk_asignacionJ_grado1_idx` (`grado_idgrado` ASC) VISIBLE,
  CONSTRAINT `fk_asignacionJ_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `calificador_creaj`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignacionJ_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `calificador_creaj`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignacionJ_grado1`
    FOREIGN KEY (`grado_idgrado`)
    REFERENCES `calificador_creaj`.`grado` (`idgrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `calificador_creaj`.`puntaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`puntaje` (
  `idpuntaje` INT NOT NULL AUTO_INCREMENT,
  `proyecto_idproyecto` INT NOT NULL,
  `usuario_idUsuario` INT NOT NULL,
  `puntaje` DECIMAL(3) NULL,
  PRIMARY KEY (`idpuntaje`, `proyecto_idproyecto`, `usuario_idUsuario`),
  INDEX `fk_puntaje_proyecto1_idx` (`proyecto_idproyecto` ASC) VISIBLE,
  INDEX `fk_puntaje_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_puntaje_proyecto1`
    FOREIGN KEY (`proyecto_idproyecto`)
    REFERENCES `calificador_creaj`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_puntaje_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `calificador_creaj`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `calificador_creaj`.`puntos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`puntos` (
  `idpuntos` INT NOT NULL AUTO_INCREMENT,
  `puntos` INT NULL,
  PRIMARY KEY (`idpuntos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `calificador_creaj`.`Ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`Ranking` (
  `idRanking` INT NOT NULL AUTO_INCREMENT,
  `proyecto_idproyecto` INT NOT NULL,
  `proyecto_grado_idgrado` INT NOT NULL,
  `proyecto_materia_idmateria` INT NOT NULL,
  `puntaje_idpuntaje` INT NOT NULL,
  PRIMARY KEY (`idRanking`, `proyecto_idproyecto`, `proyecto_grado_idgrado`, `proyecto_materia_idmateria`, `puntaje_idpuntaje`),
  INDEX `fk_Ranking_proyecto1_idx` (`proyecto_idproyecto` ASC, `proyecto_grado_idgrado` ASC, `proyecto_materia_idmateria` ASC) VISIBLE,
  INDEX `fk_Ranking_puntaje1_idx` (`puntaje_idpuntaje` ASC) VISIBLE,
  CONSTRAINT `fk_Ranking_proyecto1`
    FOREIGN KEY (`proyecto_idproyecto` , `proyecto_grado_idgrado` , `proyecto_materia_idmateria`)
    REFERENCES `calificador_creaj`.`proyecto` (`idproyecto` , `grado_idgrado` , `materia_idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ranking_puntaje1`
    FOREIGN KEY (`puntaje_idpuntaje`)
    REFERENCES `calificador_creaj`.`puntaje` (`idpuntaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `calificador_creaj`.`naprobacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificador_creaj`.`naprobacion` (
  `idnaprobacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` LONGTEXT NULL,
  `rango` VARCHAR(45) NULL,
  `nota` FLOAT NULL,
  `criterios_idcriterios` INT NOT NULL,
  PRIMARY KEY (`idnaprobacion`, `criterios_idcriterios`),
  INDEX `fk_naprovacion_criterios1_idx` (`criterios_idcriterios` ASC) VISIBLE,
  CONSTRAINT `fk_naprovacion_criterios1`
    FOREIGN KEY (`criterios_idcriterios`)
    REFERENCES `calificador_creaj`.`criterios` (`idcriterios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
